name: E2E test

on:
  pull_request:
    branches:
      - 'jorge/e2e-workflow'

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Use Node.js 18.8.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.19.0"
      - name: yarn install
        run: yarn
      - name: yarn build
        working-directory: ./agoric
        run: yarn build
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18.19.0"
      - name: yarn install
        run: yarn
      - name: yarn start:docker
        working-directory: ./agoric
        run: yarn start:docker
      - name: yarn build
        run: yarn build
      
      - name: Install linux deps
        run: |
          sudo apt-get install --no-install-recommends -y \
          fluxbox \
          xvfb

      - name: Run xvfb and fluxbox
        run: |
          Xvfb :0 -screen 0 1024x768x24 -listen tcp -ac &
          fluxbox &
        env:
          DISPLAY: :0.0
            
      - name: Run e2e tests
        working-directory: ./frontend
        uses: cypress-io/github-action@v6
        with:
          start: npx serve ui/dist -p 5173
          command: yarn test:e2e
          wait-on: 'http://localhost:5173'
          wait-on-timeout: 120
          browser: chrome
        env:
          DISPLAY: :0.0
          SECRET_WORDS: "river bargain mirror again moon sell romance attend fatal odor stove gold when canoe name basket ladder latin tag sad swear school yellow replace"

      - name: Archive e2e artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-artifacts
          path: |
              frontend/test/e2e/videos
              frontend/test/e2e/screenshots
        continue-on-error: true