name: E2E Test

on:
  push:
    branches:
      - 'jorge/e2e-workflow'

defaults:
  run:
    working-directory: frontend

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Use Node.js 18.8.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.8.x"
      - name: yarn install
        run: yarn
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18.18"
      - name: yarn install
        run: yarn
      - name: yarn start:docker
        run: yarn start:docker
      - name: Install linux deps
        run: |
          sudo apt-get install --no-install-recommends -y \
          fluxbox \
          xvfb

      - name: Run xvfb and fluxbox
        run: |
          Xvfb :0 -screen 0 1024x768x24 -listen tcp -ac &
          fluxbox &
        env:
          DISPLAY: :0.0
            
      - name: Run e2e tests
        uses: cypress-io/github-action@248bde77443c376edc45906ede03a1aba9da0462
        with:
          start: yarn dev
          command: yarn test:e2e
          wait-on: 'http://localhost:5173'
          wait-on-timeout: 120
          browser: chrome
        env:
          DISPLAY: :0.0
          CYPRESS_PRIVATE_KEY: "f20cbc1d201e368f32f2370701f3f4575063986b1dc9364cd8f01f278c9192bc"

      - name: Archive e2e artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-artifacts
          path: |
              test/e2e/videos
              test/e2e/screenshots
        continue-on-error: true
