name: E2E

on:
  push:
    branches:
      - 'jorge/e2e-ci-workflow'

jobs:
  unit:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js 18.8.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.8.x"

      - name: yarn install
        run: yarn

  integration:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18.18"
      
      - name: yarn install
        run: yarn

      - name: Start local chain
        run: yarn start:docker

      - name: Print user1 address
        id: print_user1_address
        run: echo "user1_address=$(docker exec e2e-agd-1 bash -c 'agd keys show user1 --keyring-backend=test --address')" >> $GITHUB_ENV

      - name: Print user1 private key
        id: print_user1_private_key
        run: echo "user1_private_key=$(docker exec e2e-agd-1 bash -c 'yes | agd keys export --unsafe --unarmored-hex --keyring-backend=test user1')" >> $GITHUB_ENV

      - name: Print user2 address
        id: print_user2_address
        run: echo "user2_address=$(docker exec e2e-agd-1 bash -c 'agd keys show user2 --keyring-backend=test --address')" >> $GITHUB_ENV

      - name: Print user2 private key
        id: print_user2_private_key
        run: echo "user2_private_key=$(docker exec e2e-agd-1 bash -c 'yes | agd keys export --unsafe --unarmored-hex --keyring-backend=test user2')" >> $GITHUB_ENV


      # - name: Provision user2
      #   run: docker exec e2e-agd-1 bash -c 'agd tx bank send ${{ steps.print_user1_address.outputs.user1_address }} ${{ steps.print_user2_address.outputs.user2_address }} 15000000uist --keyring-backend=test --chain-id=agoriclocal --gas=auto --gas-adjustment=1.2 --yes -b block'

      - name: Install linux deps
        run: |
          sudo apt-get install --no-install-recommends -y \
          fluxbox \
          xvfb

      - name: Run xvfb and fluxbox
        run: |
          Xvfb :0 -screen 0 1024x768x24 -listen tcp -ac &
          fluxbox &
        env:
          DISPLAY: :0.0
            
      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./frontend
          start: yarn dev
          command: yarn test:e2e 
          wait-on: 'http://localhost:5173'
          wait-on-timeout: 120
          browser: chrome
        env:
          DISPLAY: :0.0
          CYPRESS_USER1_PRIVATE_KEY: ${{ env.user1_private_key }} 
          CYPRESS_USER2_PRIVATE_KEY: ${{ env.user2_private_key }}
          PRIVATE_KEY: ${{ env.user1_private_key }}

      - name: Archive e2e artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-artifacts
          path: |
              frontend/test/e2e/videos
              frontend/test/e2e/screenshots
        continue-on-error: true
