name: Working Dir

on:
  push:
    branches:
      - 'jorge/e2e-workflow'

jobs:
  unit:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: $GITHUB_WORKSPACE/frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Working Directory
        run: pwd
          

